POST http://localhost:8080/professores
Content-Type: application/json

{
  "matricula": 20240001,
  "nome": "Valéria Ribeiro",
  "cpf": "123.456.789-00",
  "disciplinaAssociada": "Evolução",
  "departamento": "Ciências Biológicas",
  "genero": "FEMININO",
  "dataNascimento": "2024-05-01",
  "salario": 5783.55
}
