POST http://localhost:8080/alunos
Content-Type: application/json

{
  "matricula": 20240002,
  "nome": "Carla Dalila",
  "cpf": "123.456.789-00",
  "curso": "Medicina",
  "genero": "FEMININO",
  "dataNascimento": "2024-04-27"
}
