POST http://localhost:8080/alunos
Content-Type: application/json

{
  "matricula": 20240001,
  "nome": "Victor Hugo",
  "cpf": "123.456.789-00",
  "curso": "Bacharelado em Tecnologia da Informação",
  "genero": "MASCULINO",
  "dataNascimento": "2000-01-01"
}
